Test

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -31,19 +31,37 @@ jobs:
           npm install
           npm run build
 
+      - name: Install Pa11y
+        run: npm install -g pa11y
+
       - name: Start application
         run: npm start & npx wait-on http://localhost:5173
 
-      - name: Run pa11y-ci and Save Output
-        run: |
-          npm install -g pa11y-ci
-          pa11y-ci --reporter=json > pa11y_results.json
+      - name: Run Pa11y CI and Save Output
+        run: npm run pa11y-ci 2>&1 | tee pa11y_output.txt
 
-      - name: Comment PR with Pa11y Results
-        uses: thollander/actions-comment-pull-request@v2
+      - name: Read Pa11y output file
+        id: pa11y_output
+        uses: juliangruber/read-file-action@v1
         with:
-          filePath: pa11y_results.json
-          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
+          path: ./pa11y_output.txt
 
-      - name: Exit
-        run: exit 0
+      - name: Comment on pull request with Pa11y testing results
+        uses: thollander/actions-comment-pull-request@master
+        with:
+          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
+          message: |
+            <details>
+              <summary>Pa11y Testing Results</summary>
+
+              ```
+              ${{ steps.pa11y_output.outputs.content }}
+              ```
+
+            </details>
+
+      - name: Check for Pa11y failures
+        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+        run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the Pa11y CI step in the workflow for details."
+          exit 1
